import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {
  const { data: session } = useSession()
  console.log(session)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicons/favicon.ico" />
        <link rel="manifest" href="/favicons/site.webmanifest.json" />
      </Head>
      <main>
        Welcome
        <button type="button" onClick={() => signIn()}>
          signin
        </button>
        <button type="button" onClick={() => signOut()}>
          signout
        </button>
      </main>
    </>
  )
}
